
# Configure Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodcutapi-deployment
spec:
  selector:
    matchLabels:
      app: productapi-pod
  template:
    metadata:
      labels:
        app: productapi-pod
    spec:
      containers:
      - name: productapi-container
        image: faten/product:1.0.1
        resources:
          limits:
            memory: "128Mi" # 128 mili bytes
            cpu: "500m"     # 500 mili cpu
        ports:
        - containerPort: 80